<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-02-16T18:22:25 IST" name="Suite" finished-at="2025-02-16T18:22:30 IST" duration-ms="5379">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationTest.incorrectCreds()[pri:0, instance:AutomationFramework.tests.ErrorValidationTest@41330d4f]" name="incorrectCreds" class="AutomationFramework.tests.ErrorValidationTest"/>
      </group> <!-- ErrorHandling -->
    </groups>
    <test started-at="2025-02-16T18:22:25 IST" name="ErrorValidation Test" finished-at="2025-02-16T18:22:30 IST" duration-ms="5379">
      <class name="AutomationFramework.tests.ErrorValidationTest">
        <test-method is-config="true" signature="launchapp()[pri:0, instance:AutomationFramework.tests.ErrorValidationTest@41330d4f]" started-at="2025-02-16T18:22:25 IST" name="launchapp" finished-at="2025-02-16T18:22:27 IST" duration-ms="2201" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:AutomationFramework.tests.ErrorValidationTest@41330d4f]" started-at="2025-02-16T18:22:27 IST" name="ProductErrorValidation" finished-at="2025-02-16T18:22:27 IST" duration-ms="589" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null
at AutomationFramework.Pageobjects.ProductCatalogue.addPrdtocart(ProductCatalogue.java:57)
at AutomationFramework.tests.ErrorValidationTest.ProductErrorValidation(ErrorValidationTest.java:51)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:AutomationFramework.tests.ErrorValidationTest@41330d4f]" started-at="2025-02-16T18:22:28 IST" name="teardown" finished-at="2025-02-16T18:22:28 IST" duration-ms="185" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="launchapp()[pri:0, instance:AutomationFramework.tests.ErrorValidationTest@41330d4f]" started-at="2025-02-16T18:22:28 IST" name="launchapp" finished-at="2025-02-16T18:22:29 IST" duration-ms="1593" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method signature="incorrectCreds()[pri:0, instance:AutomationFramework.tests.ErrorValidationTest@41330d4f]" started-at="2025-02-16T18:22:29 IST" name="incorrectCreds" finished-at="2025-02-16T18:22:30 IST" duration-ms="348" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- incorrectCreds -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:AutomationFramework.tests.ErrorValidationTest@41330d4f]" started-at="2025-02-16T18:22:30 IST" name="teardown" finished-at="2025-02-16T18:22:30 IST" duration-ms="176" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- AutomationFramework.tests.ErrorValidationTest -->
    </test> <!-- ErrorValidation Test -->
  </suite> <!-- Suite -->
</testng-results>
